import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import tools from '@/data/tools.json';
import { blogPosts } from '@/data/blog-posts';
import ToolDetailClient from './ToolDetailClient';
import { getAffiliateLink } from '@/lib/affiliate';

type Tool = {
  id: number;
  name: string;
  description: string;
  category: 'Writing' | 'Image' | 'Productivity' | 'Code' | 'Audio' | 'Video';
  pricing: string;
  url: string;
  affiliate_link: string;
  icon_url: string;
  examples?: { prompt: string; image_url: string }[];
  needs_vpn: boolean;
  languages: string[];
  rating?: number;
  rating_count?: number;
};

// 类型断言确保数据符合我们的类型要求
const typedTools = tools as Tool[];

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> {
  const { id } = await params;
  const toolId = parseInt(id);
  const tool = typedTools.find(t => t.id === toolId);
  
  if (!tool) {
    return {
      title: 'Tool Not Found – Use AI Tools',
      description: 'The tool you are looking for could not be found.'
    };
  }
  
  const title = `${tool.name} – Use AI Tools`;
  const description = tool.description.slice(0, 160);

  const categoryFaqs: Record<string, { question: string; answer: string }[]> = {
    'Writing': [
      { question: 'Is AI writing tool suitable for beginners?', answer: 'Yes, most AI writing tools are designed with user-friendly interfaces that make them accessible to beginners. They often provide templates and guided workflows to help you get started quickly.' },
      { question: 'Can AI writing tools help with SEO?', answer: 'Absolutely! Many AI writing tools include SEO features like keyword optimization, readability analysis, and content suggestions to help your content rank better in search engines.' },
      { question: 'Is the content generated by AI writing tools plagiarism-free?', answer: 'Reputable AI writing tools generate original content. However, it\'s always recommended to run the content through a plagiarism checker before publishing.' },
    ],
    'Image': [
      { question: 'Do I need artistic skills to use AI image generators?', answer: 'No, you don\'t need artistic skills. AI image generators use text prompts to create images. With practice, anyone can learn to write effective prompts.' },
      { question: 'Can I use AI-generated images commercially?', answer: 'Most AI image generators allow commercial use of generated images, but it\'s important to check each tool\'s license terms before using them for commercial purposes.' },
      { question: 'What is the best way to write prompts for AI image generators?', answer: 'Effective prompts include details about subject, style, lighting, composition, and mood. Using specific adjectives and providing reference images can greatly improve results.' },
    ],
    'Audio': [
      { question: 'Can AI voice generators create realistic voices?', answer: 'Yes, modern AI voice generators can create incredibly realistic human-like voices with natural intonation and emotion.' },
      { question: 'Are AI voice tools suitable for podcasts?', answer: 'Absolutely! Many podcasters use AI voice tools for intros, outros, and even entire episodes. The quality has improved significantly in recent years.' },
      { question: 'Can I use AI-generated voices for commercial projects?', answer: 'Most AI voice services offer commercial licenses, but be sure to review the terms of service for each tool you use.' },
    ],
    'Video': [
      { question: 'Do I need video editing experience to use AI video tools?', answer: 'No, AI video tools are designed to simplify video creation. Many offer automated features like text-to-video, auto-subtitles, and smart editing.' },
      { question: 'Can AI generate video from text?', answer: 'Yes! Advanced AI video tools can convert text scripts into fully animated videos with AI-generated visuals, voices, and music.' },
      { question: 'What is the best AI tool for video editing?', answer: 'The best tool depends on your needs. Some excel at automated editing, while others specialize in AI-generated content. Check our video tools category for detailed comparisons.' },
    ],
    'Code': [
      { question: 'Can AI coding tools replace programmers?', answer: 'AI coding tools are designed to assist programmers, not replace them. They excel at generating boilerplate code, suggesting improvements, and helping with debugging.' },
      { question: 'Which AI coding assistant is best for beginners?', answer: 'For beginners, tools with good documentation and user-friendly interfaces work best. Many offer free tiers so you can try them out.' },
      { question: 'Do AI coding tools work with all programming languages?', answer: 'Most AI coding tools support multiple languages, but some specialize in specific languages. Check each tool\'s documentation for supported languages.' },
    ],
    'Productivity': [
      { question: 'Can AI productivity tools really save time?', answer: 'Yes! AI productivity tools can automate repetitive tasks, summarize meetings, organize information, and help you stay focused, saving hours each week.' },
      { question: 'Are AI productivity tools secure?', answer: 'Reputable productivity tools take security seriously. Look for features like end-to-end encryption, two-factor authentication, and privacy-focused policies.' },
      { question: 'Which AI productivity tool is best for teams?', answer: 'The best tool depends on your team\'s needs. Some excel at project management, while others specialize in note-taking or workflow automation.' },
    ],
  };

  const faqs = categoryFaqs[tool.category] || categoryFaqs['Productivity'];

  const jsonLd = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'SoftwareApplication',
        'name': tool.name,
        'description': tool.description,
        'applicationCategory': `https://schema.org/${tool.category}Application`,
        'operatingSystem': 'Web',
        'url': tool.url,
        'image': tool.icon_url || 'https://useaitools.me/logo.png',
        'screenshot': `https://useaitools.me/tools/${tool.id}/screenshot.png`,
        'featureList': [
          `${tool.category} AI tool`,
          `${tool.pricing} pricing`,
          tool.needs_vpn ? 'VPN required' : 'No VPN required',
          `Supports: ${tool.languages.join(', ')}`,
        ].join(', '),
        'offers': {
          '@type': 'Offer',
          'price': ['Free', 'Freemium', 'Open Source'].includes(tool.pricing) ? '0' : '9.99',
          'priceCurrency': 'USD',
          'availability': 'https://schema.org/InStock',
          'priceSpecification': {
            '@type': 'PriceSpecification',
            'price': ['Free', 'Freemium', 'Open Source'].includes(tool.pricing) ? '0' : '9.99',
            'priceCurrency': 'USD',
            'description': tool.pricing,
          },
        },
        'aggregateRating': {
          '@type': 'AggregateRating',
          'ratingValue': tool.rating ? String(tool.rating) : '4.5',
          'ratingCount': tool.rating_count ? String(tool.rating_count) : '100',
          'bestRating': '5',
          'worstRating': '1'
        },
        'review': [
          {
            '@type': 'Review',
            'author': { '@type': 'Organization', 'name': 'Use AI Tools' },
            'datePublished': '2026-01-15',
            'reviewBody': `${tool.name} is a top-rated ${tool.category.toLowerCase()} AI tool with a ${tool.pricing.toLowerCase()} pricing model. ${tool.description.slice(0, 200)}`,
            'reviewRating': {
              '@type': 'Rating',
              'ratingValue': tool.rating ? String(tool.rating) : '4.5',
              'bestRating': '5',
              'worstRating': '1'
            }
          }
        ],
        'author': {
          '@type': 'Organization',
          'name': 'Use AI Tools',
          'url': 'https://useaitools.me',
        },
        'publisher': {
          '@type': 'Organization',
          'name': 'Use AI Tools',
          'logo': {
            '@type': 'ImageObject',
            'url': 'https://useaitools.me/logo.png',
          },
        },
      },
      {
        '@type': 'FAQPage',
        'mainEntity': faqs.map((faq) => ({
          '@type': 'Question',
          'name': faq.question,
          'acceptedAnswer': {
            '@type': 'Answer',
            'text': faq.answer
          }
        }))
      }
    ]
  };

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      siteName: 'Use AI Tools',
      type: 'website',
      url: `https://useaitools.me/tools/${tool.id}`,
      locale: 'en_US',
      alternateLocale: 'zh_CN',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
    },
    alternates: {
      canonical: `https://useaitools.me/tools/${tool.id}`,
      languages: {
        'en': `/tools/${tool.id}`,
        'zh': `/tools/${tool.id}?lang=zh`,
      },
    },
    other: {
      'application/ld+json': JSON.stringify(jsonLd)
    }
  };
}

export default async function ToolDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const toolId = parseInt(id);
  const tool = typedTools.find(t => t.id === toolId);

  if (!tool) {
    notFound();
  }

  // Enrich tool with affiliate link from environment variable
  const enrichedTool = {
    ...tool,
    affiliate_link: getAffiliateLink(tool)
  };

  // Get related tools - smart recommendation algorithm
  const getRelatedTools = (): Tool[] => {
    // 1. 首先从同分类中筛选，排除当前工具
    const candidates = typedTools.filter(t => t.id !== tool.id);
    
    // 2. 计算每个工具与当前工具的匹配分数
    const scoredTools = candidates.map(t => {
      let score = 0;
      
      // 同分类 +3 分（最高优先级）
      if (t.category === tool.category) {
        score += 3;
      }
      
      // 相同定价模式 +2 分（第二优先级）
      if (t.pricing === tool.pricing) {
        score += 2;
      }
      
      // 定价模式相似（比如都是免费或都是付费）+1 分
      const isFree = (p: string) => ['Free', 'Freemium', 'Open Source'].includes(p);
      const isPaid = (p: string) => ['Paid', 'Free Trial'].includes(p);
      if ((isFree(t.pricing) && isFree(tool.pricing)) || (isPaid(t.pricing) && isPaid(tool.pricing))) {
        score += 1;
      }
      
      return { tool: t, score };
    });
    
    // 3. 按分数排序，分数相同则随机打乱
    scoredTools.sort((a, b) => {
      if (b.score !== a.score) {
        return b.score - a.score;
      }
      // 分数相同时随机排序，增加推荐多样性
      return Math.random() - 0.5;
    });
    
    // 4. 取前3个工具
    return scoredTools.slice(0, 3).map(st => st.tool);
  };
  
  const relatedTools = getRelatedTools().map(t => ({ ...t, affiliate_link: getAffiliateLink(t) }));

  const relatedArticles = blogPosts
    .filter(post => {
      const postCategory = post.category?.toLowerCase() || '';
      const toolCategory = tool.category.toLowerCase();
      return postCategory === toolCategory || postCategory.includes(toolCategory);
    })
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, 5);

  const breadcrumbLd = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    'itemListElement': [
      {
        '@type': 'ListItem',
        'position': 1,
        'name': 'Home',
        'item': 'https://useaitools.me',
      },
      {
        '@type': 'ListItem',
        'position': 2,
        'name': `${tool.category} AI Tools`,
        'item': `https://useaitools.me/category/${tool.category.toLowerCase()}`,
      },
      {
        '@type': 'ListItem',
        'position': 3,
        'name': tool.name,
        'item': `https://useaitools.me/tools/${tool.id}`,
      },
    ],
  };

  const pageJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    'name': tool.name,
    'description': tool.description,
    'applicationCategory': tool.category,
    'operatingSystem': 'Web',
    'url': tool.url,
    'offers': {
      '@type': 'Offer',
      'price': ['Free', 'Freemium', 'Open Source'].includes(tool.pricing) ? '0' : '9.99',
      'priceCurrency': 'USD',
      'availability': 'https://schema.org/InStock',
      'name': tool.pricing
    },
    'aggregateRating': {
      '@type': 'AggregateRating',
      'ratingValue': tool.rating ? String(tool.rating) : '4.5',
      'ratingCount': tool.rating_count ? String(tool.rating_count) : '100',
      'bestRating': '5',
      'worstRating': '1'
    }
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(pageJsonLd) }}
      />
      <ToolDetailClient tool={enrichedTool} relatedTools={relatedTools} relatedArticles={relatedArticles} />
    </>
  );
}
